import { toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
export const Images = {
  heroBanner:
    "https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?auto=compress&cs=tinysrgb&w=500",
  banner1:
    "https://images.pexels.com/photos/26202785/pexels-photo-26202785/free-photo-of-beagle-running-on-a-beach.jpeg?auto=compress&cs=tinysrgb&w=800",
  banner2:
    "https://images.pexels.com/photos/20839718/pexels-photo-20839718/free-photo-of-ginger-cat-lying-down.jpeg?auto=compress&cs=tinysrgb&w=800",
  banner3:
    "https://images.pexels.com/photos/459326/pexels-photo-459326.jpeg?auto=compress&cs=tinysrgb&w=800",
  downloadOnIcn: require("../utils/Images/playStore.png"),
  pug: "https://images.pexels.com/photos/1289557/pexels-photo-1289557.jpeg?auto=compress&cs=tinysrgb&w=800",
  goldenRetriever:
    "https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?auto=compress&cs=tinysrgb&w=800",
  germanShepard:
    "https://images.pexels.com/photos/333083/pexels-photo-333083.jpeg?auto=compress&cs=tinysrgb&w=800",
  persianCat:
    "https://images.pexels.com/photos/1644767/pexels-photo-1644767.jpeg?auto=compress&cs=tinysrgb&w=800",
  siameseCat:
    "https://images.pexels.com/photos/596590/pexels-photo-596590.jpeg?auto=compress&cs=tinysrgb&w=800",
  maineCoonCat:
    "https://images.pexels.com/photos/1475260/pexels-photo-1475260.jpeg?auto=compress&cs=tinysrgb&w=800",
  dogLeashAccessory:
    "https://images.pexels.com/photos/3357026/pexels-photo-3357026.jpeg?auto=compress&cs=tinysrgb&w=800",
  catScratchingAccessory:
    "https://images.pexels.com/photos/16881826/pexels-photo-16881826/free-photo-of-two-cats-lying-on-a-scratching-post.jpeg?auto=compress&cs=tinysrgb&w=800",
  dogBedAccessory:
    "https://images.pexels.com/photos/2248516/pexels-photo-2248516.jpeg?auto=compress&cs=tinysrgb&w=800",
};

export const Toast = (type: string, message: string) => {
  if (type === "success") {
    toast.success(message);
  } else if (type === "error") {
    toast.error(message);
  } else if (type === "warn") {
    toast.warn(message);
  }
};

export const SortingData = [
  { _id: 1, name: "Price: Low to High", type: "L2H" },
  { _id: 2, name: "Price: High to Low", type: "H2L" },
  { _id: 3, name: "Name: A to Z", type: "A2Z" },
  { _id: 4, name: "Name: Z to A", type: "Z2A" },
];

export const FilterData = [
  { _id: 1, name: "Below 1000", type: "<1000" },
  { _id: 2, name: "1001 - 5000", type: "1001" },
  { _id: 3, name: "5001 - 10000", type: "5001" },
  { _id: 4, name: "More than 10000", type: "10000>" },
];
export const categoryData = [
  {
    _id: 1,
    title: "Dog",
    img: "https://images.pexels.com/photos/4681107/pexels-photo-4681107.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    _id: 2,
    title: "Cat",
    img: "https://images.pexels.com/photos/45201/kitty-cat-kitten-pet-45201.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    _id: 3,
    title: "Dogs Accessories",
    img: "https://images.pexels.com/photos/5733419/pexels-photo-5733419.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    _id: 4,
    title: "Cat Accessories",
    img: "https://images.pexels.com/photos/4444017/pexels-photo-4444017.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
];

export const BannerData = [
  {
    _id: 1,
    bannerImg: Images.banner1,
  },
  {
    _id: 2,
    bannerImg: Images.banner2,
  },
  {
    _id: 3,
    bannerImg: Images.banner3,
  },
];

export const recommendedProduct = [
  {
    _id: 1,
    name: "Pug",
    slug: "pug",
    image: Images.pug,
    offerPrice: 15000,
    actualPrice: 17000,
    discountPercent: 20,
    description: "A small, friendly dog with a wrinkled face.",
    maxQuantity: 5,
    imageArray: ["", ""],
    category: "Dog",
  },
  {
    _id: 2,
    name: "Golden Retriever",
    slug: "golden-retriever",
    image: Images.goldenRetriever,
    offerPrice: 20000,
    actualPrice: 23000,
    discountPercent: 13,
    description: "A friendly and intelligent breed, great with families.",
    maxQuantity: 3,
    imageArray: ["", ""],
    category: "Dog",
  },
  {
    _id: 3,
    name: "German Shepherd",
    slug: "german-shepherd",
    image: Images.germanShepard,
    offerPrice: 18000,
    actualPrice: 20000,
    discountPercent: 10,
    description:
      "A highly active and intelligent breed, ideal for active owners. A highly active and intelligent breed, ideal for active owners. A highly active and intelligent breed, ideal for active owners.",
    maxQuantity: 4,
    imageArray: ["", ""],
    category: "Dog",
  },
  {
    _id: 4,
    name: "Persian Cat",
    slug: "persian-cat",
    image: Images.persianCat,
    offerPrice: 12000,
    actualPrice: 14000,
    discountPercent: 14,
    description: "A long-haired breed known for its flat face and round eyes.",
    maxQuantity: 6,
    imageArray: ["", ""],
    category: "Cat",
  },
  {
    _id: 5,
    name: "Siamese Cat",
    slug: "siamese-cat",
    image: Images.siameseCat,
    offerPrice: 10000,
    actualPrice: 12000,
    discountPercent: 16,
    description:
      "A breed known for its slender body and blue almond-shaped eyes.",
    maxQuantity: 5,
    imageArray: ["", ""],
    category: "Cat",
  },
  {
    _id: 6,
    name: "Maine Coon",
    slug: "maine-coon",
    image: Images.maineCoonCat,
    offerPrice: 15000,
    actualPrice: 18000,
    discountPercent: 17,
    description: "A large and sociable cat, known for its friendly nature.",
    maxQuantity: 4,
    imageArray: ["", ""],
    category: "Cat",
  },
  {
    _id: 7,
    name: "Dog Leash",
    slug: "dog-leash",
    image: Images.dogLeashAccessory,
    offerPrice: 500,
    actualPrice: 700,
    discountPercent: 28,
    description: "A durable and comfortable leash for walking your dog.",
    maxQuantity: 10,
    imageArray: ["", ""],
    category: "Accessory",
  },
  {
    _id: 8,
    name: "Cat Scratching Post",
    slug: "cat-scratching-post",
    image: Images.catScratchingAccessory,
    offerPrice: 1200,
    actualPrice: 1500,
    discountPercent: 20,
    description: "A sturdy scratching post to keep your cat entertained.",
    maxQuantity: 8,
    imageArray: ["", ""],
    category: "Accessory",
  },
  {
    _id: 9,
    name: "Pet Bed",
    slug: "pet-bed",
    image: Images.dogBedAccessory,
    offerPrice: 2500,
    actualPrice: 3000,
    discountPercent: 17,
    description: "A comfortable bed for your pet to rest and relax.",
    maxQuantity: 5,
    imageArray: ["", ""],
    category: "Accessory",
  },
];

export const CategoryData = [
  { _id: 1, title: "All", type: "all" },
  { _id: 2, title: "Accessories", type: "accessory" },
  { _id: 3, title: "Medicine", type: "medicine" },
  { _id: 4, title: "Pets", type: "pet" },
  { _id: 5, title: "Doctors", type: "doctor" },
];

export const newCategoryData = [
  {
    _id: 1,
    title: "Pet",
    slug: "pet",
    image: Images.heroBanner,
  },
  {
    _id: 2,
    title: "Accessories",
    slug: "accessories",
    image: Images.heroBanner,
  },
  {
    _id: 3,
    title: "Pet Food",
    slug: "pet-food",
    image: Images.heroBanner,
  },
  {
    _id: 4,
    title: "Pharmacy",
    slug: "pharmacy",
    image: Images.heroBanner,
  },
];

export const newSubCategoryData = [
  {
    _id: 1,
    title: "Dog",
    slug: "dog",
    category: {
      _id: 1,
      title: "Pet",
      slug: "pet",
    },
    image: Images.heroBanner,
    description:
      "Man's best friend in various breeds.Man's best friend in various breeds.Man's best friend in various breeds.",
  },
  {
    _id: 2,
    title: "Cat",
    slug: "cat",
    category: {
      _id: 1,
      title: "Pet",
      slug: "pet",
    },
    image: Images.heroBanner,
    description: "Independent and affectionate companions.",
  },
  {
    _id: 3,
    title: "Birds",
    slug: "bird",
    category: {
      _id: 1,
      title: "Pet",
      slug: "pet",
    },
    image: Images.heroBanner,
    description: "Feathered friends with beautiful songs and colors.",
  },
  {
    _id: 4,
    title: "Fish",
    slug: "fish",
    category: {
      _id: 1,
      title: "Pet",
      slug: "pet",
    },
    image: Images.heroBanner,
    description: "Aquatic pets for serene home environments.",
  },
  {
    _id: 5,
    title: "Reptile",
    slug: "reptile",
    category: {
      _id: 1,
      title: "Pet",
      slug: "pet",
    },
    image: Images.heroBanner,
    description: "Cold-blooded pets with unique needs.",
  },
  {
    id: 6,
    title: "Small Mammal",
    slug: "small-mammal",
    description: "Hamsters, guinea pigs, and other small furry pets.",
    category: {
      _id: 1,
      title: "Pet",
      slug: "pet",
    },
    image: Images.heroBanner,
  },
  {
    id: 7,
    title: "Rabbit",
    slug: "rabbit",
    description: "Cute and cuddly hopping companions.",
    category: {
      _id: 1,
      title: "Pet",
      slug: "pet",
    },
    image: Images.heroBanner,
  },
  {
    id: 8,
    title: "Ferret",
    slug: "ferret",
    description: "Playful and mischievous elongated mammals.",
    category: {
      _id: 1,
      title: "Pet",
      slug: "pet",
    },
    image: Images.heroBanner,
  },
  {
    id: 9,
    title: "Horse",
    description: "Large, majestic animals for riding and companionship.",
    category: {
      _id: 1,
      title: "Pet",
      slug: "pet",
    },
    slug: "horse",
    image: Images.heroBanner,
  },
  {
    id: 10,
    title: "Amphibian",
    description: "Frogs, toads, and other moisture-loving pets.",
    category: {
      _id: 1,
      title: "Pet",
      slug: "pet",
    },
    slug: "amphibian",
    image: Images.heroBanner,
  },
  {
    id: 11,
    title: "Dog Leash",
    description: "Durable leash for dog walks.",
    category: {
      _id: 2,
      title: "Accessories",
      slug: "accessories",
    },
    slug: "dog-leash",
    image: Images.heroBanner,
  },
  {
    id: 12,
    title: "Cat Scratching Post",
    category: "Cats",
    description: "Keeps cats entertained and their claws healthy.",
    type: "accessory",
    image: Images.heroBanner,
    totalProduct: 10,
  },
  {
    id: 13,
    title: "Bird Cage",
    category: "Birds",
    description: "Spacious and safe home for birds.",
    type: "accessory",
    image: Images.heroBanner,
    totalProduct: 10,
  },
  {
    id: 14,
    title: "Aquarium",
    category: "Fish",
    description: "Glass tank for fish and aquatic plants.",
    type: "accessory",
    image: Images.heroBanner,
    totalProduct: 10,
  },
  {
    id: 15,
    title: "Reptile Heat Lamp",
    category: "Reptiles",
    description: "Provides necessary warmth for reptiles.",
    type: "accessory",
    image: Images.heroBanner,
    totalProduct: 10,
  },
  {
    id: 16,
    title: "Hamster Wheel",
    category: "Small Mammals",
    description: "Exercise wheel for small mammals.",
    type: "accessory",
    image: Images.heroBanner,
    totalProduct: 10,
  },
  {
    id: 17,
    title: "Rabbit Hutch",
    category: "Rabbits",
    description: "Outdoor or indoor hutch for rabbits.",
    type: "accessory",
    image: Images.heroBanner,
    totalProduct: 10,
  },
  {
    id: 18,
    title: "Ferret Hammock",
    category: "Ferrets",
    description: "Comfortable hammock for ferrets to rest.",
    type: "accessory",
    image: Images.heroBanner,
    totalProduct: 10,
  },
  {
    id: 19,
    title: "Horse Saddle",
    category: "Horses",
    description: "Saddle for horseback riding.",
    type: "accessory",
    image: Images.heroBanner,
    totalProduct: 10,
  },
  {
    id: 20,
    title: "Amphibian Habitat",
    category: "Amphibians",
    description: "Enclosure for amphibians with necessary humidity.",
    type: "accessory",
    image: Images.heroBanner,
    totalProduct: 10,
  },
];

export const newProductData = [
  {
    _id: 1,
    name: "Pug",
    slug: "pug",
    image: Images.heroBanner,
    offerPrice: 15000,
    actualPrice: 17000,
    discountPercent: 20,
    description: "A small, friendly dog with a wrinkled face.",
    maxQuantity: 5,
    imageArray: ["", ""],
    category: "Dog",
  },
];

export const AllCategoryData = [
  {
    id: 1,
    name: "Dog",
    description:
      "Man's best friend in various breeds.Man's best friend in various breeds.Man's best friend in various breeds.",
    type: "pet",
    image: Images.heroBanner,
    totalProduct: 10,
  },
  {
    id: 2,
    name: "Cat",
    description: "Independent and affectionate companions.",
    type: "pet",
    image: Images.heroBanner,
    totalProduct: 10,
  },
  {
    id: 3,
    name: "Birds",
    description: "Feathered friends with beautiful songs and colors.",
    type: "pet",
    image: Images.heroBanner,
    totalProduct: 10,
  },
  {
    id: 4,
    name: "Fish",
    description: "Aquatic pets for serene home environments.",
    type: "pet",
    image: Images.heroBanner,
    totalProduct: 10,
  },
  {
    id: 5,
    name: "Reptiles",
    description: "Cold-blooded pets with unique needs.",
    type: "pet",
    image: Images.heroBanner,
    totalProduct: 10,
  },
  {
    id: 6,
    name: "Small Mammals",
    description: "Hamsters, guinea pigs, and other small furry pets.",
    type: "pet",
    image: Images.heroBanner,
    totalProduct: 10,
  },
  {
    id: 7,
    name: "Rabbits",
    description: "Cute and cuddly hopping companions.",
    type: "pet",
    image: Images.heroBanner,
    totalProduct: 10,
  },
  {
    id: 8,
    name: "Ferrets",
    description: "Playful and mischievous elongated mammals.",
    type: "pet",
    image: Images.heroBanner,
    totalProduct: 10,
  },
  {
    id: 9,
    name: "Horses",
    description: "Large, majestic animals for riding and companionship.",
    type: "pet",
    image: Images.heroBanner,
    totalProduct: 10,
  },
  {
    id: 10,
    name: "Amphibians",
    description: "Frogs, toads, and other moisture-loving pets.",
    type: "pet",
    image: Images.heroBanner,
    totalProduct: 10,
  },
  {
    id: 11,
    name: "Dog Leash",
    category: "Dogs",
    description: "Durable leash for dog walks.",
    type: "accessory",
    image: Images.heroBanner,
    totalProduct: 10,
  },
  {
    id: 12,
    name: "Cat Scratching Post",
    category: "Cats",
    description: "Keeps cats entertained and their claws healthy.",
    type: "accessory",
    image: Images.heroBanner,
    totalProduct: 10,
  },
  {
    id: 13,
    name: "Bird Cage",
    category: "Birds",
    description: "Spacious and safe home for birds.",
    type: "accessory",
    image: Images.heroBanner,
    totalProduct: 10,
  },
  {
    id: 14,
    name: "Aquarium",
    category: "Fish",
    description: "Glass tank for fish and aquatic plants.",
    type: "accessory",
    image: Images.heroBanner,
    totalProduct: 10,
  },
  {
    id: 15,
    name: "Reptile Heat Lamp",
    category: "Reptiles",
    description: "Provides necessary warmth for reptiles.",
    type: "accessory",
    image: Images.heroBanner,
    totalProduct: 10,
  },
  {
    id: 16,
    name: "Hamster Wheel",
    category: "Small Mammals",
    description: "Exercise wheel for small mammals.",
    type: "accessory",
    image: Images.heroBanner,
    totalProduct: 10,
  },
  {
    id: 17,
    name: "Rabbit Hutch",
    category: "Rabbits",
    description: "Outdoor or indoor hutch for rabbits.",
    type: "accessory",
    image: Images.heroBanner,
    totalProduct: 10,
  },
  {
    id: 18,
    name: "Ferret Hammock",
    category: "Ferrets",
    description: "Comfortable hammock for ferrets to rest.",
    type: "accessory",
    image: Images.heroBanner,
    totalProduct: 10,
  },
  {
    id: 19,
    name: "Horse Saddle",
    category: "Horses",
    description: "Saddle for horseback riding.",
    type: "accessory",
    image: Images.heroBanner,
    totalProduct: 10,
  },
  {
    id: 20,
    name: "Amphibian Habitat",
    category: "Amphibians",
    description: "Enclosure for amphibians with necessary humidity.",
    type: "accessory",
    image: Images.heroBanner,
    totalProduct: 10,
  },
];

export const productsData = [
  {
    _id: 1,
    name: "Pug",
    slug: "pug",
    image: Images.heroBanner,
    offerPrice: 15000,
    actualPrice: 17000,
    discountPercent: 20,
    description: "A small, friendly dog with a wrinkled face.",
    maxQuantity: 5,
    imageArray: [Images.pug, Images.persianCat, Images.maineCoonCat],
    category: "Dog",
    otherInfo: `<html>
  <body style="font-family: Arial, sans-serif; margin: 20px;">
    <p style="font-size: 16px; color: #333; line-height: 1.6; text-align: justify; background-color: #fff; padding: 15px; border-radius: 5px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);">
      The Pug is a small, charming dog breed known for its wrinkled face, short muzzle, and curly tail. Pugs are affectionate, playful, and good with children. Originating in China, they have a loyal and friendly temperament. Their short coat requires minimal grooming but they need regular exercise.
    </p>
    <br/>
    <table style="width: 100%; border-collapse: collapse; background-color: #fff; border: 1px solid #ddd; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); border-radius: 5px;">
      <thead>
        <tr>
          <th style="background-color: #f2f2f2; padding: 10px; text-align: left; font-size: 18px; border-bottom: 1px solid #ddd;">Product Details</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td style="padding: 10px; font-size: 16px; border-bottom: 1px solid #ddd; font-weight: bold;">Height</td>
          <td style="padding: 10px; font-size: 16px; border-bottom: 1px solid #ddd;">150cm</td>
        </tr>
      </tbody>
    </table>
  </body>
</html>`,
  },
  {
    _id: 2,
    name: "Persian Cat",
    slug: "persian-cat",
    image: Images.heroBanner,
    offerPrice: 12000,
    actualPrice: 14000,
    discountPercent: 15,
    description: "A long-haired breed of cat with a sweet personality.",
    maxQuantity: 3,
    imageArray: ["", ""],
    category: "Cat",
  },
  {
    _id: 3,
    name: "Canary",
    slug: "canary",
    image: Images.heroBanner,
    offerPrice: 3000,
    actualPrice: 3500,
    discountPercent: 14,
    description: "A small, yellow bird known for its singing ability.",
    maxQuantity: 10,
    imageArray: ["", ""],
    category: "Birds",
  },
  {
    _id: 4,
    name: "Goldfish",
    slug: "goldfish",
    image: Images.heroBanner,
    offerPrice: 500,
    actualPrice: 600,
    discountPercent: 17,
    description: "A small, orange fish popular in home aquariums.",
    maxQuantity: 20,
    imageArray: ["", ""],
    category: "Fish",
  },
  {
    _id: 5,
    name: "Labrador Retriever",
    slug: "labrador-retriever",
    image: Images.heroBanner,
    offerPrice: 20000,
    actualPrice: 22000,
    discountPercent: 9,
    description:
      "A large, friendly dog known for its loyalty and companionship.",
    maxQuantity: 4,
    imageArray: ["", ""],
    category: "Dog",
  },
  {
    _id: 6,
    name: "Siamese Cat",
    slug: "siamese-cat",
    image: Images.heroBanner,
    offerPrice: 13000,
    actualPrice: 15000,
    discountPercent: 13,
    description: "A slender, graceful cat with striking blue eyes.",
    maxQuantity: 2,
    imageArray: ["", ""],
    category: "Cat",
  },
  {
    _id: 7,
    name: "Parrot",
    slug: "parrot",
    image: Images.heroBanner,
    offerPrice: 8000,
    actualPrice: 9500,
    discountPercent: 16,
    description:
      "A colorful bird known for its ability to mimic sounds and speech.",
    maxQuantity: 7,
    imageArray: ["", ""],
    category: "Birds",
  },
  {
    _id: 8,
    name: "Betta Fish",
    slug: "betta-fish",
    image: Images.heroBanner,
    offerPrice: 700,
    actualPrice: 850,
    discountPercent: 18,
    description: "A vibrant, colorful fish known for its aggressive nature.",
    maxQuantity: 15,
    imageArray: ["", ""],
    category: "Fish",
  },
  {
    _id: 9,
    name: "Bulldog",
    slug: "bulldog",
    image: Images.heroBanner,
    offerPrice: 18000,
    actualPrice: 20000,
    discountPercent: 10,
    description:
      "A medium-sized dog known for its muscular build and wrinkled face.",
    maxQuantity: 5,
    imageArray: ["", ""],
    category: "Dog",
  },
  {
    _id: 10,
    name: "Maine Coon",
    slug: "maine-coon",
    image: Images.heroBanner,
    offerPrice: 14000,
    actualPrice: 16000,
    discountPercent: 12,
    description: "A large, sociable cat with a friendly temperament.",
    maxQuantity: 3,
    imageArray: ["", ""],
    category: "Cat",
  },
  {
    _id: 11,
    name: "German Shepherd",
    slug: "german-shepherd",
    image: Images.heroBanner,
    offerPrice: 25000,
    actualPrice: 28000,
    discountPercent: 11,
    description:
      "A large, intelligent dog known for its versatility and work ethic.",
    maxQuantity: 6,
    imageArray: ["", ""],
    category: "Dog",
  },
  {
    _id: 12,
    name: "Bengal Cat",
    slug: "bengal-cat",
    image: Images.heroBanner,
    offerPrice: 18000,
    actualPrice: 21000,
    discountPercent: 14,
    description: "A sleek, athletic cat known for its exotic appearance.",
    maxQuantity: 4,
    imageArray: ["", ""],
    category: "Cat",
  },
  {
    _id: 13,
    name: "Cockatiel",
    slug: "cockatiel",
    image: Images.heroBanner,
    offerPrice: 5000,
    actualPrice: 6000,
    discountPercent: 17,
    description:
      "A small, friendly bird known for its whistling and singing abilities.",
    maxQuantity: 8,
    imageArray: ["", ""],
    category: "Birds",
  },
  {
    _id: 14,
    name: "Angelfish",
    slug: "angelfish",
    image: Images.heroBanner,
    offerPrice: 1500,
    actualPrice: 1800,
    discountPercent: 16,
    description: "A beautiful, graceful fish popular in freshwater aquariums.",
    maxQuantity: 12,
    imageArray: ["", ""],
    category: "Fish",
  },
  {
    _id: 15,
    name: "Chihuahua",
    slug: "chihuahua",
    image: Images.heroBanner,
    offerPrice: 12000,
    actualPrice: 14000,
    discountPercent: 14,
    description: "A tiny, lively dog known for its big personality.",
    maxQuantity: 7,
    imageArray: ["", ""],
    category: "Dog",
  },
  {
    _id: 16,
    name: "Sphynx Cat",
    slug: "sphynx-cat",
    image: Images.heroBanner,
    offerPrice: 16000,
    actualPrice: 19000,
    discountPercent: 16,
    description:
      "A hairless cat known for its unique appearance and affectionate nature.",
    maxQuantity: 3,
    imageArray: ["", ""],
    category: "Cat",
  },
  {
    _id: 17,
    name: "Lovebird",
    slug: "lovebird",
    image: Images.heroBanner,
    offerPrice: 4000,
    actualPrice: 4700,
    discountPercent: 15,
    description: "A small, colorful bird known for its strong pair bonding.",
    maxQuantity: 9,
    imageArray: ["", ""],
    category: "Birds",
  },
  {
    _id: 18,
    name: "Neon Tetra",
    slug: "neon-tetra",
    image: Images.heroBanner,
    offerPrice: 300,
    actualPrice: 350,
    discountPercent: 14,
    description:
      "A small, brightly colored fish popular in community aquariums.",
    maxQuantity: 25,
    imageArray: ["", ""],
    category: "Fish",
  },
  {
    _id: 19,
    name: "Beagle",
    slug: "beagle",
    image: Images.heroBanner,
    offerPrice: 15000,
    actualPrice: 17000,
    discountPercent: 12,
    description:
      "A small to medium-sized dog known for its keen sense of smell and tracking ability.",
    maxQuantity: 5,
    imageArray: ["", ""],
    category: "Dog",
  },
  {
    _id: 20,
    name: "Ragdoll Cat",
    slug: "ragdoll-cat",
    image: Images.heroBanner,
    offerPrice: 17000,
    actualPrice: 20000,
    discountPercent: 15,
    description: "A large, affectionate cat known for its docile temperament.",
    maxQuantity: 4,
    imageArray: ["", ""],
    category: "Cat",
  },
];
